### PR TITLE
Add twoofswords v0.17.1.3

### PR DESCRIPTION
**Pull request by twoofswords**
Add assert and signature files for v0.17.1.3.

### CODE REVIEW

**Comment by binaryFate** [comment]
Please add your PGP key in ./gitian-pubkeys

**Comment by twoofswords** [comment]
My PGP key was added in pull request [85](https://github.com/monero-project/gitian.sigs/pull/85)

**Comment by binaryFate** [comment]
> My PGP key was added in pull request [85](https://github.com/monero-project/gitian.sigs/pull/85)

Indeed, my bad. My checks were failing because your key is missing in that PR branch (your branch `twoofswords:twoofswordsv0.17.1.3`), hence the confusion.

**Comment by twoofswords** [comment]
That was my bad... I forgot to fetch upstream on my local branch before I made the pull request.

**Comment by binaryFate** [comment]
> That was my bad... I forgot to fetch upstream on my local branch before I made the pull request.

no worries, thanks for contributing the deterministic builds :+1:

**Review by TheCharlatan — COMMENTED** [review]
Thanks!

**Pull request merged**
