### PR TITLE
Add hoverhalver.asc + signed assert files v0.17.3.0

### PR DESCRIPTION
**Pull request by HoverHalver**

### CODE REVIEW

**Comment by binaryFate** [comment]
`ERROR: User 'halver' doesn't have a matching PGP key.  Expected gitian-pubkeys/halver.asc`

Fix with `mv gitian-pubkeys/hoverhalver.asc gitian-pubkeys/halver.asc`

**Comment by HoverHalver** [comment]
Apologies. Hopefully it's ok now. (I don't practice github enough).

**Comment by TheCharlatan** [comment]
@HoverHalver can you try and squash the commits into either a single commit, or two commits with one adding the correct pgp key and the other adding the signatures? If you need git help, contact me on libera.chat.

**Comment by HoverHalver** [comment]
@TheCharlatan I did squash my commits into a single commit. I hope I did it right.
Please tell me if I must do something supplementary ?
Thanks.

**Comment by selsta** [comment]
Doesn't seem correct. There should be 1 or 2 commits, your PR has 5 now. Did you merge other commits manually to your master branch?

**Comment by HoverHalver** [comment]
I did the following :
- I updated my github repo (maybe I shouldn't have done that ?)
- I then updated the local repo on my local PC (`git pull`)
- I did a `git rebase -i xxx` locally, squashing the intermediate commits
- I did a `git push origin master -f` to my github repo

I feel that, having let 15 days before doing the squash, and refreshing my github repo, there is a now mix of commits which may explain the issues (?).

Anyway, I don't want to annoy too much people and to put disorder in gitian.sigs.
If it is too complicated now to disentangle the mess I have done, I feel it is better to just close this PR now.
I'll retry with the next gitian build, and I'll try to do it more properly.
The issue is that I use git/github only from time to time, and this doesn't help.
Apologies for the mess.
(Neverteless, Merry Christmas to everybody !)

**Comment by selsta** [comment]
If I don't forget I can write you exact git steps on how to fix it :)

**Comment by selsta** [comment]
Guess I have time now. On the computer with the repo do the following:

```
cd gitian.sigs
git remote add upstream https://github.com/monero-project/gitian.sigs
git fetch upstream
git rebase -i upstream/master
```

Then set all the commits that don't belong to this PR to `d` so that they get dropped. Afterwards force push to master again.

```
git push -f
```

That *hopefully* should work.

**Comment by HoverHalver** [comment]
I just did those steps.
The (possible) problem is that, when doing 
```
$ torsocks git rebase -i upstream/master
Successfully rebased and updated refs/heads/master.
```
I got only one commit displayed, the one which is the rebase basis.
So, no commit to drop or squash.

```
$ git push -f
Username for 'https://github.com': HoverHalver
Password for 'https://HoverHalver@github.com': 
Enumerating objects: 23, done.
Counting objects: 100% (23/23), done.
Delta compression using up to 2 threads
Compressing objects: 100% (17/17), done.
Writing objects: 100% (17/17), 21.42 KiB | 5.35 MiB/s, done.
Total 17 (delta 6), reused 1 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
To https://github.com/HoverHalver/gitian.sigs
 + 54e9fcd...a9cea43 master -> master (forced update)

```

**Comment by selsta** [comment]
It does look correct now.

**Review by TheCharlatan — APPROVED** [review]

**Pull request merged**
