### PR TITLE
Add v0.14.1.0

### PR DESCRIPTION
**Pull request by dikdust**
added win/lin assert/sig files done with ubuntu 18.04

### CODE REVIEW

**Comment by jonathancross** [comment]
After completing my own gitian build, I can confirm that:
1. The resulting builds in `out_manifest` match those provided here in this PR.
2. The gpg signatures on the assert files are valid and match the key key `0x144D6E86DA9446B8`.  Note the pubkey is not available on keyservers, but is available in the account of @dikdust [here via github api](https://api.github.com/users/dikdust/gpg_keys).

**Comment by TheCharlatan** [comment]
When running `./gitian-build.py` with the `--verify` argument, for example `./gitian-build.py --verify TheCharlatan v0.14.1.0`, the repository is checked out at the `v0.14.1.0` tag. Gitian then expects the version number in the .assert file to match the one in the descriptor (which is currently set to 0.14). If it does not find the file with the accepted version, the gitian script will fail. So for the time being, we should stick to whatever the descriptors provide us with and not change anything manually.

**Comment by TheCharlatan** [comment]
@dikdust can you squash these commits together?

**Comment by dikdust** [comment]
Done it

**Pull request closed without merging**
