### PR TITLE
added v0.14.1.x - asc file

### PR DESCRIPTION
**Pull request by dikdust**
I hope that now is correct ... Thank you for helping me @TheCharlatan  and  @jonathancross  ... Please continue to do it, I don't want to give up ;)

### CODE REVIEW

**Comment by dikdust** [comment]
> Please avoid closing PRs and opening new ones (this is your 5th) -- it creates a lot of noise and is frustrating for anyone reviewing your work. -- Thanks.
Ok sorry but "I'm learning by doing" and this is my first project as a contributor. What is the correct behaviour in this case ? (I have opened the first when there is  only @TheCharlatan PR, the other two for 1.1 and 1.2 and the fourth and fifth when you asked squashing them, at the end it will be four PR not five or there is a "better way"  ?)
> 
> Unfortunately you still have 3 commits rather than the goal of 1 and it is still deleting the contents of our README.md file...
.-. 


> 
> As long as the gpg signatures are valid, I don't see why @TheCharlatan or I can't just PR this for you -- should we do that?
Yes please for me is better at the moment (anyway until september I can't do anything). I hope that one day I will stop fighting with git but in the meaning time if you and @TheCharlatan think is better I can stop contributing. I don't want to waste your time while I'm learning ;)

**Comment by jonathancross** [comment]
> Yes please for me is better at the moment (anyway until september I can't do anything).

Okay.

> I hope that one day I will stop fighting with git but in the meaning time if you and @TheCharlatan think is better I can stop contributing. I don't want to waste your time while I'm learning ;)

Don't get me wrong, your contributions are definitely appreciated  :-)
We need as many people as possible verifying the builds.

I also completely understand how challenging `git` can be -- it has taken me a long time to get where I am with all this and I still run into difficult situations often.  Learning git / github is very useful, but I understand if you don't want to spend hours learning all of this right now -- it takes a lot of effort and time.

**Comment by jonathancross** [comment]
+invalid
per #21

**Comment by dikdust** [comment]
thanks again and again (for the future :P)

**Pull request closed without merging**
