### PR TITLE
Add MoneroArbo v0.17.1.6

### PR DESCRIPTION
**Pull request by MoneroArbo**

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Your signature for the freebsd hashes is missing.

**Comment by MoneroArbo** [comment]
Fixed, I think. This is all new to me.

But it was missing because FreeBSD is missing from the "Signing assert files" section at https://github.com/monero-project/monero/blob/master/contrib/gitian/README.md

**Comment by TheCharlatan** [comment]
Thank you for the pr. You should also learn to squash your commits together, but I don't think it matters much here, so I'll merge :)

**Comment by MoneroArbo** [comment]
Yeah ngl I was really bumbling through that guide. I'll get it better next time and maybe also try to refine the instructions for complete noobs like myself

**Pull request merged**
