### PR TITLE
Add One-horse-wagon v0.18.1.2

### PR DESCRIPTION
**Pull request by One-horse-wagon**

### CODE REVIEW

**Comment by selsta** [comment]
The files have to be in 

```
v0.18.1.2-android/one-horse-wagon/*.assert
v0.18.1.2-android/one-horse-wagon/*.assert.sig
```

Currently they are in the top level directory.

**Comment by selsta** [comment]
This was an example for the folder structure, don't name it literally a `*`. Also make sure to write your username `one-horse-wagon` and not `One-horse-wagon`.

Here you did everything correctly: https://github.com/monero-project/gitian.sigs/pull/219

**Comment by One-horse-wagon** [comment]
Thank you for looking at it.  You gave me a couple of more pointers
as to what I am doing wrong.  I am familiar with the file structure in
Linux but moving around the file structure in Github is another matter, 
so far.

**Comment by selsta** [comment]
You can't use the Github web interface for this.

**Comment by One-horse-wagon** [comment]
Ahh.  I didn't know that because I've been pounding away at it.

**Pull request closed without merging**
