### PR TITLE
Add one-horse-wagon v0.18.1.1

### PR DESCRIPTION
**Pull request by One-horse-wagon**

### CODE REVIEW

**Comment by One-horse-wagon** [comment]
This is my second pull request.  My first one was filed 5 days ago for v0.18.1.0 and has my pub key.  This second one is for v0.18.1.2.  Please accept both of them.

**Comment by binaryFate** [comment]
Thanks for contributing hashes.
Note that I get an early error when verifying them from the verify-merge script. A git error when pulling the branch, so probably something trivial.
You can debug yourself by executing 
```./verify-merge.py --pull_id 218 --version v0.18.1.1``` (218 is the number of this PR)

**Comment by selsta** [comment]
@One-horse-wagon please open a new pull request with a branch named `v0.18.1.1` instead of opening from `master`.

**Comment by One-horse-wagon** [comment]
I closed the pull request and made a new one with branch v0.18.1.1

Thank you for your help.

one-horse-wagon

**Pull request closed without merging**
