### PR TITLE
Add one-horse-wagon v0.18.1.2

### PR DESCRIPTION
**Pull request by One-horse-wagon**

### CODE REVIEW

**Comment by selsta** [comment]
Now you only have to move it in the correct directories and then force push.

**Comment by One-horse-wagon** [comment]
I reorganized all into the proper directories as you suggested.  Thank you again Selsta, for pointing out the direction to go.

**Comment by selsta** [comment]
It looks correct now. Do you know how to squash your commits to a single one?

**Comment by plowsof** [comment]
Thank you One-horse-wagon!

**Comment by One-horse-wagon** [comment]
No I don't.  Is there a command for it?

**Comment by One-horse-wagon** [comment]
I'll look up the procedure and do it.  It's a little bit more than a 
single command I see.
one-horse-wagon

**Comment by selsta** [comment]
```
git rebase --interactive HEAD~2
```

Then you change the second line the `pick` to a `s` and save.

**Pull request closed without merging**
